---
- fail: msg="unsupported vesion {{ php_minor_version }}"
  when: php_minor_version not in php_role_supported_versions

- include_tasks: php56.yml
  when: (php_minor_version == '5.6')
- include_tasks: php70.yml
  when: (php_minor_version == '7.0')
- include_tasks: php72.yml
  when: (php_minor_version == '7.2')

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  become: false
