---
- name: restart php5-fpm
  service: name=php5-fpm state=restarted enabled=yes
  become: true
  become_user: root

- name: restart php5.6-fpm
  service: name=php5.6-fpm state=restarted enabled=yes
  become: true
  become_user: root
