---
- name: restart php-fpm
  service: name={{ php_fpm_service_name }} state=restarted enabled=yes
  become: true
  become_user: root

- name: restart php53-fpm
  service: name=php53-fpm state=restarted enabled=yes
  become: true
  become_user: root

- name: restart php5.6-fpm
  service: name=php5.6-fpm state=restarted enabled=yes
  become: true
  become_user: root

- name: restart php7.0-fpm
  service: name=php7.0-fpm state=restarted enabled=yes
  become: true
  become_user: root

- name: restart php7.2-fpm
  service: name=php7.2-fpm state=restarted enabled=yes
  become: true
  become_user: root
