---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: ansible_php70_trusty
    image: ubuntu:trusty
  - name: ansible_php70_xenial
    image: ubuntu:xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: php70
verifier:
  name: testinfra
  lint:
    name: flake8
