---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: ansible_php71_trusty
    image: ubuntu:trusty
  - name: ansible_php71_xenial
    image: ubuntu:xenial
  - name: ansible_php71_bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: php71
verifier:
  name: testinfra
  lint:
    name: flake8
